### ISSUE TITLE
I can not find data/METR-LA_prior.npy file.

### ISSUE THREAD

**Issue by verystrongjoe** [HyunWookL/PM-MemNet#2]
I found distanced based adjacency matrix from the other github repo. But what about data/METR-LA_prior.npy file?  You should have mentioned about it.  Please update README to get the file or how to generate the file.  Thanks

**Comment by HyunWookL** [comment]
We have uploaded our prior files now, so you can utilize our model now!

Sorry for your inconvenience.

**Comment by verystrongjoe** [comment]
Thanks
